Update README.md
HackAtUCI/irvinehacks-site-2024 pull request #251
Opened 2024-01-17 01:15 UTC by IanWearsHat

2024-01-19 20:00 UTC, samderanova requested changes
Thanks so much for taking care of this! A few suggestions:

2024-01-19 20:00 UTC, samderanova commented on README.md
> +This project uses Docker for testing api methods locally.
Suggestion: Could you elaborate in this section about the local MongoDB application that runs on `http://localhost:8081` when running `pnpm dev`?

2024-02-03 18:07 UTC, samderanova approved these changes

2024-02-05 04:16 UTC, alexanderl19 approved these changes

2024-02-06 23:09 UTC, merged