Add form links to mentor and volunteer section
HackAtUCI/irvinehacks-site-2024 pull request #49
Opened 2023-11-30 06:40 UTC by samderanova

Replace the placeholder links in `MentorVolunteer.tsx` with the appropriate links.

2023-11-30 06:54 UTC, taesungh requested changes
Could we use redirects and have named endpoints, e.g. `/mentor`, `/volunteer`?

2023-11-30 22:57 UTC, IanWearsHat approved these changes
The buttons redirect to the correct links, so it looks good to me!

2023-12-15 06:18 UTC, rileysw submitted a review, later dismissed

2023-12-16 04:35 UTC, rileysw approved these changes

2023-12-16 04:52 UTC, taesungh approved these changes
Looks good.

2023-12-16 04:56 UTC, merged